words = ["pramit",
         "surupa",
         "tom",
         "mango",
         "apple",
         "cricket",
         "football",
         "jenny",
         "phone",
         "laptop",
         "chicken",
         "virat",
         "dhoni",
         "sourav",
         "attitude",
         "whatsapp",
         "watch"]